"""Export only numeric glyph templates into a self-contained extension."""
import base64
import hashlib
import json
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]


def main():
    source = ROOT / 'models/ocr_model.npz'
    with np.load(source, allow_pickle=False) as model:
        packed = {
            'version': str(model['version'].item()),
            'sourceSha256': hashlib.sha256(source.read_bytes()).hexdigest(),
            'labels': model['labels'].tolist(),
            'soft': base64.b64encode(model['soft'].astype('<f4').tobytes()).decode('ascii'),
            'binary': base64.b64encode(model['binary'].astype('uint8').tobytes()).decode('ascii'),
        }
    destination = ROOT / 'extension/model.js'
    destination.write_text('// Generated by export_extension_model.py\n'
                           'globalThis.EZPostModel = Object.freeze('
                           + json.dumps(packed, separators=(',', ':')) + ');\n', encoding='utf-8')
    print(f'Exported {destination.stat().st_size} bytes')


if __name__ == '__main__':
    main()
